module.exports = [
  {
    title: "Wireless Bluetooth Headphones",
    brand: "SoundMax",
    category: "Electronics",
    description: "Comfort fit, deep bass, 30 hours battery.",
    price: 1499,
    mrp: 1999,
    stock: 25,
    image: "https://via.placeholder.com/600x400?text=Headphones",
    rating: 4.4,
    numReviews: 120,
  },
  {
    title: "Smart Fitness Band",
    brand: "FitPro",
    category: "Electronics",
    description: "Steps, sleep, heart rate tracking, water resistant.",
    price: 999,
    mrp: 1499,
    stock: 40,
    image: "https://via.placeholder.com/600x400?text=Fitness+Band",
    rating: 4.2,
    numReviews: 80,
  },
  {
    title: "Men's Casual Sneakers",
    brand: "UrbanWalk",
    category: "Fashion",
    description: "Lightweight sneakers for daily wear.",
    price: 1799,
    mrp: 2499,
    stock: 18,
    image: "https://via.placeholder.com/600x400?text=Sneakers",
    rating: 4.1,
    numReviews: 65,
  },
  {
    title: "Stainless Steel Water Bottle (1L)",
    brand: "HydroLite",
    category: "Home",
    description: "Keeps drinks cold/hot for hours.",
    price: 499,
    mrp: 799,
    stock: 60,
    image: "https://via.placeholder.com/600x400?text=Water+Bottle",
    rating: 4.6,
    numReviews: 210,
  },
  {
    title: "Laptop Backpack 15.6 inch",
    brand: "CarryPro",
    category: "Accessories",
    description: "Padded laptop compartment with USB port.",
    price: 899,
    mrp: 1299,
    stock: 32,
    image: "https://via.placeholder.com/600x400?text=Backpack",
    rating: 4.3,
    numReviews: 150,
  },
];
